[package]
name = "caw_core"
version = "0.1.0"
edition = "2021"
description = "Core types for caw software-defined modular synthesizer"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
license = "MIT"
homepage = "https://github.com/gridbugs/caw.git"
repository = "https://github.com/gridbugs/caw.git"
documentation = "https://docs.rs/caw_core"

[features]
default = ["midi"]
midi = ["midly"]
web = ["getrandom/js"]

[dependencies]
anyhow = "1.0.75"
rand = "0.8"
getrandom = "0.2"
midly = { version = "0.5", optional = true }
caw_proc_macros = { path = "../proc-macros", default-features = false }
cpal = "0.15"
log = "0.4"

[[example]]
name = "cgp_example"